### ISSUE TITLE
Container Image Sizes should be smaller

### ISSUE THREAD

**Issue by fossul** [fossul/fossul#23]
**What should be added?**
Describe what should be added in detail. Provide any implementation ideas and detail. If this is to replace existing functionality also provide those details.

**Why is it needed?**
Describe why this is needed in detail? What value will result? What can we do if this enhancement is implemented?

**Comment by ktenzer** [comment]
Now using git releases to provide binaries. Added dockerfile and template for OpenShift to deploy binaries as an option to doing build. This results in a much smaller container image.
