### ISSUE TITLE
Investigate Kubernetes snapshot capabilities

### ISSUE THREAD

**Issue by fossul** [fossul/fossul#25]
**What should be added?**
K8s snapshot provider is alpha. Storage solutions will likely integrate over time reducing need for snapshot code in storage plugin.

**Why is it needed?**
Look into how this could be used in context of fossil and the capabilities, does it change how storage plugins behave? Do we need additional capabilities to leverage k8s snapshots? Should this be default to use if storage plugin is not otherwise provided?

**Comment by ktenzer** [comment]
This has been completed. Currently CSI snapshot are implemented for recovery though you need to create a new PVC not restore in-place the PVC.
